### ISSUE TITLE
Twilio instead of smsified

### ISSUE THREAD

**Issue by sckott** [mheadd/derbycityfood#1]
SMSified isn't accepting signups anymore.  Do you know of if Twilio will work instead of smsified in your derbycityfood repo? Do you know of a twilio.class.php file anywhere?

**Comment by mheadd** [comment]
I think they just closed the beta period. I expect they'll launch a full production service soon.

I've not tried to integrate Twillio, but it should be relatively straightforward to do so. You can also try Plivo (http://www.plivo.com/) and Nexmo (http://nexmo.com/).

**Comment by sckott** [comment]
Great, thanks for the help. I will check em out.
